name: ChatControl
main: kangarko.chatcontrol.ChatControl
version: 5.1.6
author: kangarko
soft-depend: [AuthMe, Essentials, Multiverse-Core, ProtocolLib, RushCore, SimpleClans, Towny, Vault]
commands: 
  chatcontrol:
    aliases: [chatc, chc]
    description: Main ChatControl command. Type /chatcontrol list for commands.
permissions:
    chatcontrol.notify.overrideranged:
        default: false
    chatcontrol.notify.whenmentioned:
        default: true
        description: Play sound to player when notified by another player and function is enabled.
    chatcontrol.broadcaster.view:
        default: true
        description: View timed messages from auto broadcaster.